# Colors (Authur)

[colors.primary]
background = '#1c1c1c'
foreground = '#ddeedd'

[colors.normal]
black   = '#3d352a'
red     = '#cd5c5c'
green   = '#86af80'
yellow  = '#e8ae5b'
blue    = '#6495ed'
magenta = '#deb887'
cyan    = '#b0c4de'
white   = '#bbaa99'

[colors.bright]
black   = '#554444'
red     = '#cc5533'
green   = '#88aa22'
yellow  = '#ffa75d'
blue    = '#87ceeb'
magenta = '#996600'
cyan    = '#b0c4de'
white   = '#ddccbb'

[colors.cursor]
cursor = '#ddeedd'

[colors.hints]
start = { foreground = '#1d1f21', background = '#e9ff5e' }
end = { foreground = '#e9ff5e', background = '#1d1f21' }

[colors.search]
matches = { foreground = '#000000', background = '#ffffff' }
focused_match = { foreground = '#ffffff', background = '#000000' }
